### ISSUE TITLE
編碼檔頭

### ISSUE THREAD

**Issue by Droidtown** [Chenct-jonathan/Loc_zai_and_Rep_zai_parser#2]
https://github.com/Chenct-jonathan/Loc_zai_and_Rep_zai_parser/blob/a457cde33349f59c50d4166ba10aa2ec3504ba2e/toolbox/text_tool.py#L1

強烈建議在設計 NLP 的相關程式時，在檔頭加上
```python
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
```
以免在某些機器上發生莫名奇妙的編碼錯誤。

**Comment by Chenct-jonathan** [comment]
fixed
